sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    dead = false
    pause(1000)
    dead = true
})
let dead = false
let Pac_man = sprites.create(img`
    . . . . . f f f f f . . . . 
    . . . f f 5 5 5 5 5 f f . . 
    . . f 5 5 5 5 f 1 5 5 5 f . 
    . f 5 5 5 5 5 f 1 5 5 5 5 f 
    . f 5 5 5 5 5 f f 5 5 5 5 f 
    . f 5 5 5 5 5 5 5 5 5 f f . 
    f 5 5 5 5 5 5 5 f f f . . . 
    f 5 5 5 5 5 5 5 f f f . . . 
    . f 5 5 5 5 5 5 5 5 5 f f . 
    . f 5 5 5 5 5 5 5 5 5 5 5 f 
    . . f 5 5 5 5 5 5 5 5 5 f . 
    . . . f 5 5 5 5 5 5 5 f . . 
    . . . . f f 5 5 5 f f . . . 
    . . . . . . f f f . . . . . 
    `, SpriteKind.Player)
info.setLife(5)
Pac_man.setPosition(170, 170)
scene.cameraFollowSprite(Pac_man)
scene.setBackgroundColor(15)
tiles.setCurrentTilemap(tilemap`level1`)
controller.moveSprite(Pac_man, 100, 100)
pause(5000)
dead = true
let ft1 = sprites.create(img`
    . . . . f f 1 1 1 1 f f . . . 
    . . . f b 1 1 1 1 1 1 b f . . 
    . . . f 1 1 1 1 1 1 1 1 f . . 
    . . f d 1 1 1 1 1 1 1 1 d f . 
    . . f d 1 1 1 1 1 1 1 1 d f . 
    . . f d d d 1 1 1 1 d d d f . 
    . . f b d b f d d f b d b f . 
    . . f c d c f 1 1 f c d c f . 
    . . . f b 1 1 1 1 1 1 b f . . 
    . . f f f c d b 1 b d f f f f 
    f c 1 1 1 c b f b f c 1 1 1 c 
    f 1 b 1 b 1 f f f f 1 b 1 b 1 
    f b f b f f f f f f b f b f b 
    . . . . . f f f f f f . . . . 
    . . . . . . . f f f . . . . . 
    `, SpriteKind.Enemy)
ft1.setPosition(170, 170)
let ft2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
ft2.setPosition(170, 170)
let ft3 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
ft3.setPosition(170, 170)
let ft4 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
ft4.setPosition(170, 170)
let ft5 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
ft5.setPosition(170, 170)
game.onUpdate(function () {
    if (dead == true) {
        ft1.follow(Pac_man, 60)
        ft2.follow(Pac_man, 80)
        ft3.follow(Pac_man, 40)
        ft4.follow(Pac_man, 30)
        ft5.follow(Pac_man, 20)
    } else {
        ft1.follow(Pac_man, 60)
    }
})
